project:
  type: website
  resources:
    "_redirects"
    
execute:
  freeze: auto

website:
  title: "Ella Kaye"
  site-url: https://ellakaye.co.uk
  description: Personal website, portfolio and blog
  repo-url: https://github.com/EllaKaye/ellakaye.co.uk
  #repo-actions: issue
  image: images/logo.png
  navbar:
    #logo: ELLAKAYE-logo-light.png
    title: "ELLA<span class='icon-line'></span>KAYE"
    right:
      - text: about
        href: about.qmd
      - text: posts
        href: posts.qmd
      - text: talks
        href: talks.qmd
      - text: packages
        href: packages.qmd
      - text: community
        href: community.qmd
      - text: contact
        href: contact.qmd
      #- icon: github
      #  href: https://github.com/EllaKaye
      #- icon: twitter
      #  href: https://twitter.com/ellamkaye
  favicon: images/favicon.png
  twitter-card: 
    title: Ella Kaye
    description: The personal website of Ella Kaye
    image: images/logo.png
    image-alt: |
      A square logo made from Ella Kaye's name - 
      first name on top of last name in dark gray capital letters, 
      separated by a horizontal bright pink line, on a very light grey background
    image-width: 500
    image-height: 500
    card-style: summary # alternative summary_large_image
    creator: "@ellamkaye"
    site: "@ellamkaye"
  open-graph: 
    #description: The personal website of Ella Kaye
    image: images/logo.png
    image-alt: |
      A square logo made from Ella Kaye's name - 
      first name on top of last name in dark gray capital letters, 
      separated by a horizontal bright pink line, on a very light grey background
    image-width: 500
    image-height: 500
    locale: en-GB
  google-analytics:
    tracking-id: "G-7G8FLLRS4M"
    anonymize-ip: true

format:
  html:
    theme: 
      light: assets/ek-theme-light.scss
      dark: assets/ek-theme-dark.scss
    css: assets/ek-styles.css
    code-block-border-left: true
    highlight-style: 
      light: assets/ek-light.theme
      dark: assets/ek-dark.theme
    smooth-scroll: true
    link-external-newwindow: true
    
editor: source

